name: Check GitHub Status

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run status check
      run: python ./github_status.py > status.txt
    - name: Upload status
      uses: actions/upload-artifact@v2
      with:
        name: status
        path: status.txt
